export const SWITCH_LANG = "SWITCH_LANG";
export const SWITCH_LANG_PICKER_VISIBILITY = "SWITCH_LANG_PICKER_VISIBILITY";
export const SWITCH_OFF_CANVAS_VISIBILITY = "SWITCH_OFF_CANVAS_VISIBILITY";
export const SWITCH_PATH_LOCATION = "SWITCH_PATH_LOCATION";